/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_AT = 1,
  sym_comment_markup_name = 2,
  sym_comment_markup_lines = 3,
  anon_sym_COLON = 4,
  anon_sym_LPAREN = 5,
  aux_sym__user_token1 = 6,
  anon_sym_RPAREN = 7,
  aux_sym__full_uri_token1 = 8,
  sym_uri = 9,
  aux_sym__text_token1 = 10,
  anon_sym_SLASH = 11,
  anon_sym_SQUOTE = 12,
  anon_sym_DQUOTE = 13,
  anon_sym_BQUOTE = 14,
  anon_sym_LT = 15,
  anon_sym_LBRACK = 16,
  anon_sym_LBRACE = 17,
  anon_sym_DOT = 18,
  anon_sym_COMMA = 19,
  anon_sym_SEMI = 20,
  anon_sym_BANG = 21,
  anon_sym_QMARK = 22,
  anon_sym_BSLASH = 23,
  anon_sym_RBRACE = 24,
  anon_sym_RBRACK = 25,
  anon_sym_GT = 26,
  anon_sym_DASH = 27,
  sym_name = 28,
  sym_invalid_token = 29,
  sym_source = 30,
  sym_comment_markup = 31,
  sym_tag = 32,
  sym__user = 33,
  sym__full_uri = 34,
  sym__text = 35,
  sym__stop_char = 36,
  sym__end_char = 37,
  aux_sym_source_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_AT] = "@",
  [sym_comment_markup_name] = "comment_markup_name",
  [sym_comment_markup_lines] = "comment_markup_lines",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [aux_sym__user_token1] = "user",
  [anon_sym_RPAREN] = ")",
  [aux_sym__full_uri_token1] = "_full_uri_token1",
  [sym_uri] = "uri",
  [aux_sym__text_token1] = "_text_token1",
  [anon_sym_SLASH] = "/",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_LT] = "<",
  [anon_sym_LBRACK] = "[",
  [anon_sym_LBRACE] = "{",
  [anon_sym_DOT] = ".",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_BANG] = "!",
  [anon_sym_QMARK] = "\?",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_RBRACE] = "}",
  [anon_sym_RBRACK] = "]",
  [anon_sym_GT] = ">",
  [anon_sym_DASH] = "-",
  [sym_name] = "name",
  [sym_invalid_token] = "invalid_token",
  [sym_source] = "source",
  [sym_comment_markup] = "comment_markup",
  [sym_tag] = "tag",
  [sym__user] = "_user",
  [sym__full_uri] = "_full_uri",
  [sym__text] = "text",
  [sym__stop_char] = "_stop_char",
  [sym__end_char] = "text",
  [aux_sym_source_repeat1] = "source_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_AT] = anon_sym_AT,
  [sym_comment_markup_name] = sym_comment_markup_name,
  [sym_comment_markup_lines] = sym_comment_markup_lines,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym__user_token1] = aux_sym__user_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym__full_uri_token1] = aux_sym__full_uri_token1,
  [sym_uri] = sym_uri,
  [aux_sym__text_token1] = aux_sym__text_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_name] = sym_name,
  [sym_invalid_token] = sym_invalid_token,
  [sym_source] = sym_source,
  [sym_comment_markup] = sym_comment_markup,
  [sym_tag] = sym_tag,
  [sym__user] = sym__user,
  [sym__full_uri] = sym__full_uri,
  [sym__text] = sym__text,
  [sym__stop_char] = sym__stop_char,
  [sym__end_char] = sym__text,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_markup_name] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_markup_lines] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__user_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__full_uri_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_uri] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_invalid_token] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_markup] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__user] = {
    .visible = false,
    .named = true,
  },
  [sym__full_uri] = {
    .visible = false,
    .named = true,
  },
  [sym__text] = {
    .visible = true,
    .named = false,
  },
  [sym__stop_char] = {
    .visible = false,
    .named = true,
  },
  [sym__end_char] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
};

static const TSCharacterRange sym_uri_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'#', '&'}, {'(', '('}, {'*', '+'}, {'-', '-'}, {'/', '9'}, {'<', '='},
  {'@', '['}, {'^', '_'}, {'a', '|'}, {'~', 0x10ffff},
};

static const TSCharacterRange aux_sym__text_token1_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'#', '&'}, {'*', '+'}, {'0', '9'}, {'=', '='}, {'A', 'Z'}, {'^', '_'},
  {'a', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 39,
        '"', 31,
        '\'', 30,
        '(', 18,
        ')', 20,
        ',', 37,
        '-', 45,
        '.', 36,
        '/', 29,
        ':', 17,
        ';', 38,
        '<', 33,
        '>', 44,
        '?', 40,
        '@', 9,
        '[', 34,
        '\\', 41,
        ']', 43,
        '`', 32,
        'h', 14,
        '{', 35,
        '}', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (('_' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(1);
      END_STATE();
    case 3:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(19);
      END_STATE();
    case 4:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '!', 6,
        '"', 6,
        '\'', 6,
        ')', 6,
        ',', 6,
        '.', 6,
        ':', 6,
        ';', 6,
        '>', 6,
        '?', 6,
        '\\', 6,
        ']', 6,
        '`', 6,
        '}', 6,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead)) ADVANCE(22);
      END_STATE();
    case 6:
      if ((!eof && set_contains(sym_uri_character_set_1, 12, lookahead))) ADVANCE(22);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 39,
        '"', 31,
        '\'', 30,
        '(', 18,
        ')', 20,
        ',', 37,
        '-', 45,
        '.', 36,
        '/', 29,
        ':', 17,
        ';', 38,
        '<', 33,
        '>', 44,
        '?', 40,
        '@', 9,
        '[', 34,
        '\\', 41,
        ']', 43,
        '`', 32,
        'h', 27,
        '{', 35,
        '}', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment_markup_name);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 's') ADVANCE(11);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment_markup_name);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment_markup_name);
      if (lookahead == 'p') ADVANCE(10);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment_markup_name);
      if (lookahead == 't') ADVANCE(12);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment_markup_name);
      if (lookahead == 't') ADVANCE(13);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment_markup_name);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment_markup_lines);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym__user_token1);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__full_uri_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_uri);
      ADVANCE_MAP(
        '!', 6,
        '"', 6,
        '\'', 6,
        ')', 6,
        ',', 6,
        '.', 6,
        ':', 6,
        ';', 6,
        '>', 6,
        '?', 6,
        '\\', 6,
        ']', 6,
        '`', 6,
        '}', 6,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead)) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 's') ADVANCE(24);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == ':') ADVANCE(2);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == 'p') ADVANCE(23);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == 't') ADVANCE(25);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == 't') ADVANCE(26);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if ((!eof && set_contains(aux_sym__text_token1_character_set_1, 11, lookahead))) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 7, .external_lex_state = 2},
  [2] = {.lex_state = 7, .external_lex_state = 2},
  [3] = {.lex_state = 7, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 7, .external_lex_state = 2},
  [6] = {.lex_state = 7, .external_lex_state = 2},
  [7] = {.lex_state = 7, .external_lex_state = 2},
  [8] = {.lex_state = 7, .external_lex_state = 2},
  [9] = {.lex_state = 7, .external_lex_state = 2},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_comment_markup_name] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(1),
    [aux_sym__text_token1] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_invalid_token] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(12),
    [sym_comment_markup] = STATE(13),
    [sym_tag] = STATE(2),
    [sym__full_uri] = STATE(2),
    [sym__text] = STATE(2),
    [sym__stop_char] = STATE(5),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(9),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(11),
    [aux_sym__text_token1] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [sym_name] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_tag] = STATE(3),
    [sym__full_uri] = STATE(3),
    [sym__text] = STATE(3),
    [sym__stop_char] = STATE(5),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(9),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(11),
    [aux_sym__text_token1] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [sym_name] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_tag] = STATE(3),
    [sym__full_uri] = STATE(3),
    [sym__text] = STATE(3),
    [sym__stop_char] = STATE(5),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_AT] = ACTIONS(21),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(24),
    [aux_sym__text_token1] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_BQUOTE] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_QMARK] = ACTIONS(21),
    [anon_sym_BSLASH] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [sym_name] = ACTIONS(30),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_AT] = ACTIONS(33),
    [sym_comment_markup_name] = ACTIONS(35),
    [anon_sym_COLON] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_RPAREN] = ACTIONS(33),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(33),
    [aux_sym__text_token1] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_BQUOTE] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_DOT] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(33),
    [anon_sym_QMARK] = ACTIONS(33),
    [anon_sym_BSLASH] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(33),
    [sym_name] = ACTIONS(33),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(39),
    [anon_sym_AT] = ACTIONS(39),
    [anon_sym_COLON] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(39),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(39),
    [aux_sym__text_token1] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(39),
    [anon_sym_BQUOTE] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_LBRACE] = ACTIONS(39),
    [anon_sym_DOT] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_BANG] = ACTIONS(39),
    [anon_sym_QMARK] = ACTIONS(39),
    [anon_sym_BSLASH] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(39),
    [sym_name] = ACTIONS(39),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(43),
    [anon_sym_RPAREN] = ACTIONS(43),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(43),
    [aux_sym__text_token1] = ACTIONS(45),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_DQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(43),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_BSLASH] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(43),
    [sym_name] = ACTIONS(43),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(47),
    [anon_sym_COLON] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_RPAREN] = ACTIONS(47),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(47),
    [aux_sym__text_token1] = ACTIONS(49),
    [anon_sym_SLASH] = ACTIONS(47),
    [anon_sym_SQUOTE] = ACTIONS(47),
    [anon_sym_DQUOTE] = ACTIONS(47),
    [anon_sym_BQUOTE] = ACTIONS(47),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(47),
    [anon_sym_SEMI] = ACTIONS(47),
    [anon_sym_BANG] = ACTIONS(47),
    [anon_sym_QMARK] = ACTIONS(47),
    [anon_sym_BSLASH] = ACTIONS(47),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_RBRACK] = ACTIONS(47),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_DASH] = ACTIONS(47),
    [sym_name] = ACTIONS(47),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [anon_sym_AT] = ACTIONS(51),
    [anon_sym_COLON] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_RPAREN] = ACTIONS(51),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(51),
    [aux_sym__text_token1] = ACTIONS(53),
    [anon_sym_SLASH] = ACTIONS(51),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(51),
    [anon_sym_BQUOTE] = ACTIONS(51),
    [anon_sym_LT] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_LBRACE] = ACTIONS(51),
    [anon_sym_DOT] = ACTIONS(51),
    [anon_sym_COMMA] = ACTIONS(51),
    [anon_sym_SEMI] = ACTIONS(51),
    [anon_sym_BANG] = ACTIONS(51),
    [anon_sym_QMARK] = ACTIONS(51),
    [anon_sym_BSLASH] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_RBRACK] = ACTIONS(51),
    [anon_sym_GT] = ACTIONS(51),
    [anon_sym_DASH] = ACTIONS(51),
    [sym_name] = ACTIONS(51),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [anon_sym_AT] = ACTIONS(55),
    [anon_sym_COLON] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(55),
    [aux_sym__full_uri_token1] = ACTIONS(3),
    [sym_uri] = ACTIONS(55),
    [aux_sym__text_token1] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(55),
    [anon_sym_SQUOTE] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(55),
    [anon_sym_BQUOTE] = ACTIONS(55),
    [anon_sym_LT] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(55),
    [anon_sym_DOT] = ACTIONS(55),
    [anon_sym_COMMA] = ACTIONS(55),
    [anon_sym_SEMI] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(55),
    [anon_sym_QMARK] = ACTIONS(55),
    [anon_sym_BSLASH] = ACTIONS(55),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(55),
    [anon_sym_GT] = ACTIONS(55),
    [anon_sym_DASH] = ACTIONS(55),
    [sym_name] = ACTIONS(55),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(61), 1,
      aux_sym__full_uri_token1,
    STATE(8), 1,
      sym__end_char,
    ACTIONS(59), 14,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_BSLASH,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_GT,
  [23] = 4,
    ACTIONS(3), 1,
      aux_sym__full_uri_token1,
    ACTIONS(63), 1,
      anon_sym_COLON,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym__user,
  [36] = 2,
    ACTIONS(3), 1,
      aux_sym__full_uri_token1,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
  [43] = 2,
    ACTIONS(3), 1,
      aux_sym__full_uri_token1,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
  [50] = 2,
    ACTIONS(69), 1,
      aux_sym__user_token1,
    ACTIONS(71), 1,
      aux_sym__full_uri_token1,
  [57] = 2,
    ACTIONS(3), 1,
      aux_sym__full_uri_token1,
    ACTIONS(73), 1,
      anon_sym_COLON,
  [64] = 2,
    ACTIONS(71), 1,
      aux_sym__full_uri_token1,
    ACTIONS(75), 1,
      sym_comment_markup_lines,
  [71] = 2,
    ACTIONS(3), 1,
      aux_sym__full_uri_token1,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
  [78] = 2,
    ACTIONS(3), 1,
      aux_sym__full_uri_token1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
  [85] = 2,
    ACTIONS(3), 1,
      aux_sym__full_uri_token1,
    ACTIONS(81), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 23,
  [SMALL_STATE(12)] = 36,
  [SMALL_STATE(13)] = 43,
  [SMALL_STATE(14)] = 50,
  [SMALL_STATE(15)] = 57,
  [SMALL_STATE(16)] = 64,
  [SMALL_STATE(17)] = 71,
  [SMALL_STATE(18)] = 78,
  [SMALL_STATE(19)] = 85,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stop_char, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stop_char, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__text, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__text, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_char, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__end_char, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__full_uri, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__full_uri, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [67] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_markup, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__user, 3, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_name = 0,
  ts_external_token_invalid_token = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_name] = sym_name,
  [ts_external_token_invalid_token] = sym_invalid_token,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_name] = true,
    [ts_external_token_invalid_token] = true,
  },
  [2] = {
    [ts_external_token_name] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_comment_external_scanner_create(void);
void tree_sitter_comment_external_scanner_destroy(void *);
bool tree_sitter_comment_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_comment_external_scanner_serialize(void *, char *);
void tree_sitter_comment_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_comment(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_comment_external_scanner_create,
      tree_sitter_comment_external_scanner_destroy,
      tree_sitter_comment_external_scanner_scan,
      tree_sitter_comment_external_scanner_serialize,
      tree_sitter_comment_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "comment",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 3,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
